encoding: utf-8
name: 彩程设计博客
description: 彩程设计官方博客

markdown: redcarpet
highlighter: pygments
exclude: ['LICENSE', 'README.md', 'bower.json', 'Gemfile', 'Gemfile.lock']
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'
permalink: '/:year/:month/:day/:title.html'

sass:
  sass_dir: assets/stylesheets
